version: '3.7'

services:
  web:
    build: ./app
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    environment:
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=works_single_view
      - SQL_USER=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    