# Generated by Django 2.1.7 on 2019-04-15 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None)),
                ('iswc', models.CharField(max_length=11, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None)),
                ('source_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
            ],
        ),
    ]
