# Generated by Django 2.1.7 on 2019-04-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works_single_view_app', '0002_auto_20190412_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmetadata',
            name='iswc',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
